export const FETCH_TVSHOWS = 'containers/TVSHOWSPage/FETCH_TVSHOWS'
export const FETCH_TVSHOWS_SUCCESS = 'containers/TVSHOWSPage/FETCH_TVSHOWS_SUCCESS'
export const FETCH_TVSHOWS_FAIL = 'containers/TVSHOWSPage/FETCH_TVSHOWS_FAIL'

export const SEARCH_TVSHOWS = 'containers/TVSHOWSPage/SEARCH_TVSHOWS'
export const SEARCH_TVSHOWS_SUCCESS = 'containers/TVSHOWSPage/SEARCH_TVSHOWS_SUCCESS'
export const SEARCH_TVSHOWS_FAIL = 'containers/TVSHOWSPage/SEARCH_TVSHOWS_FAIL'
